### ISSUE TITLE
How to import existing m3U playlists

### ISSUE THREAD

**Issue by vexillia** [olegantonyan/mpz#110]
This is probably an enhancement request because I couldn't find a way to do this.  If there is please tell me.

**Comment by olegantonyan** [comment]
Currently it's not possible. The only exception is internet radio playlists. The only reason why this is the case is to avoid duplicated tracks when you have a folder with files and m3u for these files along the way. Adding this folder will give you all the files plus the content of m3u. I used to hate this in other players. In your opinion, what is expected behavior in this case?

**Comment by vexillia** [comment]
I would expect to be able to import and export playlists.  The former is important for new users with lots of existing playlists and the latter for that no longer wish to use mpz.  Otherwise it's a "tie-in".

**Comment by olegantonyan** [comment]
Done in version 1.0.5
m3u can be loaded explicitly by clicking on it in directory view, but ignored when adding directories recursively

**Comment by vexillia** [comment]
Thank you.
