### ISSUE TITLE
Support GNOME 3 desktop themes

### ISSUE THREAD

**Issue by rjd1** [olegantonyan/mpz#144]
Add support for GNOME 3 desktop themes. At least in 3.38.5 on Pop_OS! 21.04 (and presumably with Ubuntu), switching between Light & Dark modes has no effect.

**Comment by olegantonyan** [comment]
This is because mpz is Qt5 application and Gtk themes do not apply for Qt applications unless you (or distro's maintainers) make it do so, and it's far from perfect. Try this https://www.linuxuprising.com/2018/05/get-qt5-apps-to-use-native-gtk-style-in.html

Having Gtk and Qt applications follow the single desktop theme is general pain in a butt on Linux

**Comment by rjd1** [comment]
Thanks for the info and link - that solution did work for me. Nice that it also had the effect of getting some other apps to adopt the theme, namely VLC. My eyes feel better already!
